import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'pendaftaran/pendaftaran',
        'pemtk/pemtk',
        'orang-kompeten/orang-kompeten'
      ],
    },
    {
      type: 'category',
      label: 'Orang Kompeten',
      items: [
        {
          type: 'category',
          label: 'Keselamatan',
          items: [
            {
              type: 'category',
              label: 'Operator Dandang Stim',
              items: [
                'orang-kompeten/ods/ods-gred1',
                'orang-kompeten/ods/ods-gred2',
              ],
            },
            {
              type: 'category',
              label: 'Operator Kren Menara',
              items: [
                'orang-kompeten/kren/kren-menara-daftar',
                'orang-kompeten/kren/kren-menara-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Operator Kren Bergerak Beroda',
              items: [
                'orang-kompeten/kren/kren-bergerakberoda-daftar',
                'orang-kompeten/kren/kren-bergerakberoda-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Operator Kren Bergerak Berantai',
              items: [
                'orang-kompeten/kren/kren-bergerakberantai-daftar',
                'orang-kompeten/kren/kren-bergerakberantai-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Major Hazard',
              items: [
                'orang-kompeten/major-hazard/major-hazard-daftar',
                'orang-kompeten/major-hazard/major-hazard-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Keselamatan Kesihatan',
              items: [
                'orang-kompeten/keselamatan-kesihatan/keselamatan-kesihatan-daftar',
                'orang-kompeten/keselamatan-kesihatan/keselamatan-kesihatan-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Keselamatan Tapak',
              items: [
                'orang-kompeten/keselamatan-tapak/keselamatan-tapak-daftar',
                'orang-kompeten/keselamatan-tapak/keselamatan-tapak-renewal',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Higien',
          items: [
            {
              type: 'category',
              label: 'Penguji Gas Bertauliah dan Penyelia Kemasukan',
              items: [
                'orang-kompeten/agtes/agtes-daftar',
                'orang-kompeten/agtes/agtes-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Juruteknik Higien 2',
              items: [
                'orang-kompeten/higien-2/higien-2-daftar',
                'orang-kompeten/higien-2/higien-2-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Penaksir Risiko Bising',
              items: [
                'orang-kompeten/risiko-bising/risiko-bising-daftar',
                'orang-kompeten/risiko-bising/risiko-bising-renewal',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Pengurusan Kimia',
          items: [
            {
              type: 'category',
              label: 'Juruteknik Higien 1',
              items: [
                'orang-kompeten/higien-1/higien-1-daftar',
                'orang-kompeten/higien-1/higien-1-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Penaksir Kualiti Udara Dalaman',
              items: [
                'orang-kompeten/kualiti-udara/kualiti-udara-daftar',
                'orang-kompeten/kualiti-udara/kualiti-udara-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Pengapit',
              items: [
                'orang-kompeten/pengapit/pengapit-daftar',
                'orang-kompeten/pengapit/pengapit-renewal',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Kesihatan Pekerjaan',
          items: [
            {
              type: 'category',
              label: 'Doktor Kesihatan',
              items: [
                'orang-kompeten/doktor-kesihatan/doktor-kesihatan-daftar',
                'orang-kompeten/doktor-kesihatan/doktor-kesihatan-renewal',
              ],
            },
            {
              type: 'category',
              label: 'Medical Surveillance',
              items: [
                'orang-kompeten/kualiti-udara/kualiti-udara-daftar',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'OSH-Coordinator',
          items: [
            'orang-kompeten/higien-1/higien-1-daftar',
          ],
        },

        'orang-kompeten/pembatalan-permohonan',
        'orang-kompeten/pembayaran-fi',
        'orang-kompeten/kelulusan-permohonan',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: ['loji/intro'],
    },
    {
      type: 'category',
      label: 'Bantuan',
      items: [
        {
          type: 'category',
          label: 'FAQ',
          link: {
            type: 'doc',
            id: 'FAQ/faq',
          },
          items: [
            'FAQ/tk',
            'FAQ/loji',
            'FAQ/oyk',
          ],
        },
      ],
    },
  ],

};

export default sidebars;